### PR TITLE
Create sum.py

### PR DESCRIPTION
**Pull request by aiiimzzz634**

### CODE REVIEW

**Review by aiiimzzz634 — COMMENTED** [review]
hacktoberfest

**Comment by aiiimzzz634** [comment]
hacktoberfest

**Comment by aiiimzzz634** [comment]
hacktoberfest

**Comment by aiiimzzz634** [comment]
hacktoberfest

**Comment by aiiimzzz634** [comment]
hacktoberfest

**Comment by aiiimzzz634** [comment]
hacktoberfest

**Comment by Mindslayer001** [comment]
Hi @aiiimzzz634, thank you for checking out my repository! I created this repository solely to store my solutions for Codeforces problems for future reference. It is not intended for the Hacktoberfest event or any other contribution purposes, so please refrain from submitting contributions. Thanks for understanding!

**Pull request closed without merging**
